### ISSUE TITLE
Do you also support other -e flags?

### ISSUE THREAD

**Issue by charliwest** [linuxserver/docker-mariadb-armhf#9]
Hello,

Just trying out this image for the first time. I see on the official mariadb image they support MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD as flags to use against the creation. Should this also support that? I tried adding them but nothing happened, it just started a blank mariadb instance.

```
docker create --name=mariadb -p 3306:3306 -e PUID=1010 -e PGID=1010 -e MYSQL_ROOT_PASSWORD=mypassword -e MYSQL_DATABASE=iSpindle -e MYSQL_USER=iSpindle -e MYSQL_PASSWORD=ohyeah -v /etc/timezone:/etc/timezone -v /etc/localtime:/etc/localtime -v /storage/mariadb/config:/config -v /storage/mariadb/mysql:/var/lib/mysql lsioarmhf/mariadb
```

```
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
+--------------------+
```

Thanks

David

**Comment by tobbenb** [comment]
Every environment variable we support is in the Readme, so no, we do not use the same variables as the official image. You need to connect to the the database with some software or exec into the container and execute commands.
